# Generated by Django 4.2.5 on 2023-10-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincontent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
