# Generated by Django 4.2.5 on 2023-10-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontent', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
