# Generated by Django 4.2.5 on 2023-10-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontent', '0004_alter_email_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
